In [1]:
import numpy as np

In [3]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [7]:
print(x+y)
print(np.add(x,y))

[ 6  8 10 12]
[ 6  8 10 12]


In [10]:
print(x-y)
print(np.subtract(x,y))
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))

[-4 -4 -4 -4]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In [12]:
x = np.array([1,2,3,4]).reshape(2,2)
y = np.array([5,6,7,8]).reshape(2,2)

In [18]:
print(x)
print('\n', y)
print('\n x+y:', x+y)
print('\n x-y:', x-y)
print('\n x*y:', x*y)
print('\n x/y:', x/y)

[[1 2]
 [3 4]]

 [[5 6]
 [7 8]]

 x+y: [[ 6  8]
 [10 12]]

 x-y: [[-4 -4]
 [-4 -4]]

 x*y: [[ 5 12]
 [21 32]]

 x/y: [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [22]:
x = np.array([1,2,3,4])
print(np.sqrt(x))
print(np.exp(x))
print(np.power(x,2))

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 1  4  9 16]


In [26]:
X = np.array([1,2,3,4]).reshape(2,2)
print(X)
print(X.mean())
print(X.mean(axis=1)) # average of rows
print(X.mean(axis=0)) # average of cols

[[1 2]
 [3 4]]
2.5
[1.5 3.5]
[2. 3.]


In [27]:
print(X.sum())
print(X.sum(axis=1)) # sum of rows
print(X.sum(axis=0)) # sum of cols

10
[3 7]
[4 6]


In [28]:
print(X.max())
print(X.min())
print(X.std())

4
1
1.118033988749895


In [29]:
X

array([[1, 2],
       [3, 4]])

In [31]:
print(X+3) # numpy 'broadcasts' the 3 to every node in the array or in other words ensures that the shape is the smae

[[4 5]
 [6 7]]


In [32]:
Y = np.arange(9).reshape(3,3)
print(Y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [36]:
x = np.arange(3)
print(x)

[0 1 2]


In [37]:
print(Y + x) # using broadcasting again to add [0,1,2] to each row in the 2d array

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [41]:
z = x.reshape(3,1)
print(z)
print(Y)

[[0]
 [1]
 [2]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [43]:
print(z + Y) # adds 0 to first row, 1 to second row and 2 to third row

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [48]:
x = np.array([1,2,3,4])
y = np.ones((4,1), dtype=int)

print(x)
print(y)
print(x*y)

[1 2 3 4]
[[1]
 [1]
 [1]
 [1]]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
