In [1]:
import numpy as np

In [19]:
x = np.arange(0,25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [20]:
# Use Boolean indexing to select elements greater than 10
# So basically, instead of indicies we are using a boolnean expression
print(x[x> 10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [21]:
print(x[x>=7])

[ 7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [22]:
print(x[(x>7) & (x<17)])

[ 8  9 10 11 12 13 14 15 16]


In [23]:
# Use boolean indexing to assign any values that are greater than 7 and less than 17 to -1
x[(x>7) & (x<17)] = -1
print(x)

In [28]:
# Sets: Intersection, Section & Union
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])

print(np.intersect1d(x,y))
print(np.setdiff1d(x,y))
print(np.union1d(x,y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [36]:
x = np.random.randint(0,11, size=(10,))
print(x)

[ 7  5  0  8  9  1  7  0  1 10]


In [37]:
# Sort function does NOT sort the array in place
print(np.sort(x))
print(x)

[ 0  0  1  1  5  7  7  8  9 10]
[ 7  5  0  8  9  1  7  0  1 10]


In [40]:
# Sort only the unique values in x
print(np.sort(np.unique(x)))

[ 0  1  5  7  8  9 10]


In [43]:
x = np.random.randint(1,11, size=(5,5))
print(x)

[[10  7  3  2  6]
 [ 6  2  6  2  8]
 [ 2  6  7  5  1]
 [ 9  9  8  8  9]
 [ 4  3  3  2  2]]


In [45]:
y = np.sort(x, axis=0)
print(y)

[[ 2  2  3  2  1]
 [ 4  3  3  2  2]
 [ 6  6  6  2  6]
 [ 9  7  7  5  8]
 [10  9  8  8  9]]


In [46]:
y = np.sort(x, axis=1)
print(y)

[[ 2  3  6  7 10]
 [ 2  2  6  6  8]
 [ 1  2  5  6  7]
 [ 8  8  9  9  9]
 [ 2  2  3  3  4]]


In [47]:
x = np.arange(1, 26).reshape(5,5)
x[x%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])