In [1]:
import numpy as np

## Slicing Arrays

There are three ways to slice arrays.

**NOTE specifying `end_index` is non-inclusive**

```
x[start_index:end_index] 
x[:end_index]
x[start_index:]
```

In [2]:
x = np.array([1,2,3,4,5])

In [4]:
a = x[1:3]
print(a)

[2 3]


In [6]:
b = x[:4]
print(b)

[1 2 3 4]


In [10]:
example1 = x[0:4]
example2 = x[:4]

print(example1)
print(example2)

[1 2 3 4]
[1 2 3 4]


In [11]:
c = x[2:]
print(c)

[3 4 5]


In [12]:
a1 = np.arange(0, 20)
print(a1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [22]:
s1 = a1[4:8] # [4  5  6  7]
s2 = a1[:9] # [0  1  2  3  4  5  6  7 8]
s3 = a1[7:17] # [ 7  8  9 10 11 12 13 14 15 16 ]
s4 = a1[5:] # [5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

In [25]:
x = np.arange(1,21).reshape(4,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [26]:
# Get the bottom right corner 9 elements only using 2D slicing
z = x[1:4, 2:5]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [27]:
# Since these are at the end we can just leave out the end_index like so
z1 = x[1:, 2:]
print(z1)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [29]:
y = x[:3, 2:]
print(y)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [34]:
# Get all the rows in column 2
# Notice how this returns a rank 1 array
print(x[:,2])

[ 3  8 13 18]


In [38]:
# When we specify the end index for the columns we get a rank 2 array returned
print(x[:,2:3])

[[ 3]
 [ 8]
 [13]
 [18]]


### Slicing and assigning to new variables

Its important to note that slicing and assigning the result to a new variable **does not** copy the value into that variable. So that means that the new variable is a pointer to the original variable.

```
x = np.array([0,1,2])
z = x[:]
```

Now varibale `z`and `x` point to the same array instance!

``` 
x[0] = 9
print(z[0]) # 9
```

In Numpy parlance we say that *slicing creates a VIEW of the original array*.

So the main takeaway is the the view is always the same slice or 'window' into the underlying Numpy array.

Lets take a look at some examples below:

In [52]:
x = np.array([0,1,2,])
z = x[:]
print('x: ', x)
print('z: ', z)
x[0] = 9
print('z: ' , z)

x:  [0 1 2]
z:  [0 1 2]
z:  [9 1 2]


In [53]:
# So thinking that this is a VIEW is quite useful from a database point of 'view' LOL
t1 = np.arange(1,19).reshape(3,6)
v1 = t1[:, 4:5]
# print(t1)
print(v1)
t1[0,4] = 7
print(v1)

[[ 5]
 [11]
 [17]]
[[ 7]
 [11]
 [17]]


In [59]:
# Use COPY command to create a completely separate new array when slicing
t2 = np.arange(1,19).reshape(3,6)
c2 = t2[:, 4:5].copy()
t2[0,4] = 7

print('t2: ', t2)
print('c2: ', c2)

t2:  [[ 1  2  3  4  7  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
c2:  [[ 5]
 [11]
 [17]]


### Using arrays as indicies for making selections in other arrays

We can use another array as indicies for making selections / slices in other arrays. Lets see some examples.

In [63]:
indices = np.array([1,3])
print(indices)

[1 3]


In [65]:
x = np.arange(1,21).reshape(4,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [67]:
# Lets use the indices to select the 2nd (index 1) and 4th row (index 3) of x
y = x[indices, :]
print(y)

[[ 6  7  8  9 10]
 [16 17 18 19 20]]


In [69]:
z = x[:, indices]
print(z)

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


In [74]:
# The 'k' value in the diag function defaults to 0 (see examples using k below)
d = np.diag(x)
print(d)

[ 1  7 13 19]


In [75]:
# Move the selected diagonal row up by 1 using k=1
d = np.diag(x, k=1)
print(d)

[ 2  8 14 20]


In [77]:
# Move the selected diagonal row down by 1 using k=-1
d = np.diag(x, k=-1)
print(d)

[ 6 12 18]


In [81]:
# Finding unique values in an array
x = np.array([[4,5,3],[3,4,6],[4,5,8]])
print(np.unique(x))

[3 4 5 6 8]
