In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
print('1st element: ', a[0])

1st element:  1


In [5]:
print('1st element (-ve index access): ', a[-5])

1st element (-ve index access):  1


In [7]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print('Element at (0,1): ', x[0,1])

Element at (0,1):  2


In [10]:
x = np.array([1,2,3,4,5])
y = np.delete(x, [0,4])
print(y)

[2 3 4]


In [18]:
y = np.arange(0,9).reshape(3,3)
print(y)
w = np.delete(y, 1, axis=0)
print('\n', w)
c = np.delete(y, 2, axis=1)
print('\n', c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[0 1 2]
 [6 7 8]]

 [[0 1]
 [3 4]
 [6 7]]


In [19]:
x = np.array([1,2,3,4,5])
y = np.append(x, 6)
print(y)

[1 2 3 4 5 6]


In [21]:
z = np.append(y, [7,8])
print(z)

[1 2 3 4 5 7 8 7 8]


In [25]:
x = np.arange(0,9).reshape(3,3)
y = np.append(x,[[9,10,11]],axis=0)
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [26]:
x = np.arange(0,9).reshape(3,3)
y = np.append(x, [[9],[10],[11]], axis=1)
print(y)

[[ 0  1  2  9]
 [ 3  4  5 10]
 [ 6  7  8 11]]


In [29]:
x = np.array([1,2,5,6,7])
y = np.insert(x, 2, [3,4])
print(y)

[1 2 3 4 5 6 7]


In [33]:
Y = np.array([[1,2,3],[7,8,9]])
print(Y)
z = np.insert(Y, 1, [4,5,6], axis=0)
print('\n', z)

[[1 2 3]
 [7 8 9]]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
v = np.insert(Y, 1, [5,7], axis=1)
print(v)

[[1 5 2 3]
 [7 7 8 9]]


In [38]:
x = np.array([1,2])
print(x)

[1 2]


In [39]:
y = np.array([[3,4], [5,6]])
print(y)

[[3 4]
 [5 6]]


In [41]:
z = np.vstack((x,y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [43]:
z = np.hstack((y, x.reshape(2,1)))
print(z)

[[3 4 1]
 [5 6 2]]
