In [1]:
import numpy as np

In [6]:
x=np.array([1,2,3,4,5])

In [8]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
x.dtype

dtype('int64')

In [10]:
x.shape

(5,)

In [12]:
y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [13]:
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
y.shape

(4, 3)

In [38]:
y.size

12

In [39]:
y.ndim

2

In [18]:
 sta = np.array(['hello', 'world'])

In [22]:
print('shape: ', sta.shape)
print('size: ', sta.size)
print('dtype: ', sta.dtype)
print('type: ', type(sta))

shape:  (2,)
size:  2
dtype:  <U5
type:  <class 'numpy.ndarray'>


In [31]:
# Different types in same array
t = np.array([1,2.5,4,3.6])
print(t, 'dtype: ', t.dtype)

[1.  2.5 4.  3.6] dtype:  float64


In [30]:
# Perhaps its safer to specify the dtype
t = np.array([1,2.5,4,3.6], dtype=np.int64)
print(t, 'dtype: ', t.dtype)

[1 2 4 3] dtype:  int64


In [32]:
np.save('my_array', y)

In [34]:
z='Nothing here yet!'
print(z)

Nothing here yet!


In [35]:
z=np.load('my_array.npy')

In [36]:
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
y = np.zeros((2, 3, 4))

In [41]:
print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [42]:
y.shape

(2, 3, 4)

In [19]:
X = np.random.randint(0,5001,size=20000).reshape(1000,20)

In [21]:
print(X)
print(np.size(X))
print(np.shape(X))

[[3039  898 2718 ...  420 4546 2017]
 [2764  192 1109 ... 1155 2476 3469]
 [4648 1579 3426 ... 3281  273 1356]
 ...
 [3296 4782  748 ... 3909  589 1677]
 [4420 3369 2181 ... 3365 4727 1914]
 [3059 2654 4003 ...  859 4843 2753]]
20000
(1000, 20)


In [ ]:
X = X.