In [23]:
import numpy as np

In [24]:
x = np.zeros((2,3), dtype=int)
print(x)

[[0 0 0]
 [0 0 0]]


In [25]:
y = np.ones((5, 5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
z = np.full((2,4), 7)
print(z)
print(z.dtype)

[[7 7 7 7]
 [7 7 7 7]]
int64


In [29]:
# Create identity matrix (a square array with diaganal 1s and 0s elsewhere)
i = np.eye(5, dtype=int)
print(i)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [30]:
d = np.diag([10,20,40,80])
print(d)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 40  0]
 [ 0  0  0 80]]


In [32]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [33]:
x = np.arange(8, 16)
print(x)

[ 8  9 10 11 12 13 14 15]


In [36]:
x = np.arange(0, 99, 10)
print(x)

[ 0 10 20 30 40 50 60 70 80 90]


In [38]:
x = np.linspace(0, 25, 10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [39]:
x = np.linspace(0, 25, 10, endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [41]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [43]:
np.reshape(x,(2,10)) 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [44]:
np.reshape(x,(4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
x = np.arange(20).reshape((2,10))
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [50]:
x = np.random.random((3,3))
print(x)

[[0.60063862 0.05021221 0.94910848]
 [0.70321016 0.13074546 0.46446321]
 [0.90675557 0.94877549 0.93311178]]


In [52]:
x = np.random.randint(4, 15, (3, 2))
print(x)

[[11  9]
 [14  8]
 [13  7]]


In [54]:
# create a 1000 x 1000 array containing random normally distrubuted 
# values with a mean of 0 and standard deviation of 0.1 
x = np.random.normal(0, 0.1, (1000, 1000))
print(x)

[[-0.09423241 -0.0322946  -0.0421677  ... -0.01260869  0.09648101
   0.08501988]
 [-0.20215761 -0.10038448 -0.10358075 ...  0.10320076 -0.05960943
   0.08320875]
 [ 0.03232266 -0.06737445  0.0755727  ...  0.02693668 -0.04656276
   0.1656584 ]
 ...
 [ 0.08072836 -0.08017582 -0.13355707 ...  0.05621989  0.1314405
   0.05277867]
 [ 0.01772682 -0.15024606  0.05162175 ...  0.18744441  0.00937841
   0.15177633]
 [ 0.12834899 -0.06087182  0.0627362  ... -0.09252537  0.21742161
  -0.12752826]]


In [63]:
print('Mean: ', x.mean())
print('Standard Deviation: ', x.std())
print('Max: ', x.max())
print('Min: ', x.min())
print('# Positive: ', (x > 0).sum())
print('# Negative: ', (x < 0).sum())

Mean:  -0.00011078238591962202
Standard Deviation:  0.0999137833078028
Max:  0.46150650111448144
Min:  -0.4530422591246464
# Positive:  499939
# Negative:  500061
